export const SET_MESSAGE_ERROR = "SET_MESSAGE_ERROR";
export const SET_MESSAGE_INFO = "SET_MESSAGE_INFO";
export const SET_MESSAGE_SUCCESS = "SET_MESSAGE_SUCCESS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
