import { Base, BaseAdmin } from "../layouts";
import {
  HomePage,
  Dashboard,
  Customers,
  Features,
  AddOrders,
  Products,
  Settings,
  Register,
  Account,
  AddFeatures,
  AddCustomers,
  Checkout,
  Orders,
  PasswordReset,
  OrderEdit,
  OrderDetailPublic,
} from "../pages";
import {
  CustomerDetail,
  ProductDetail,
  OrderDetail,
} from "../pages/private/details";
import { Categorie } from "../pages/public/listing/Categorie";
import Cart from "../pages/public/Cart";
import Login from "../pages/public/Login";
import Produit from "../pages/public/listing/Produit";
import { Reset } from "../pages/public/Reset";
import { AddProducts } from "../pages/private/AddProducts";

export const List = [
  {
    exact: true,
    path: "/",
    layout: Base,
    component: HomePage,
    protected: false,
    roles: [],
  },

  {
    exact: true,
    path: "/categorie/:title",
    layout: Base,
    component: Categorie,
    protected: false,
    roles: [],
  },

  {
    exact: true,
    path: "/admin",
    layout: BaseAdmin,
    component: Dashboard,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/account/login",
    layout: Base,
    component: Login,
    protected: false,
    roles: [],
  },
  {
    exact: true,
    path: "/account/register",
    layout: Base,
    component: Register,
    protected: false,
    roles: [],
  },
  {
    exact: true,
    path: "/account",
    layout: Base,
    component: Account,
    protected: true,
    roles: ["guest", "seller", "admin"],
  },
  {
    exact: true,
    path: "/account/orders/:id(\\d+)",
    layout: Base,
    component: OrderDetailPublic,
    protected: true,
    roles: ["guest", "seller", "admin"],
  },
  {
    exact: true,
    path: "/cart",
    layout: Base,
    component: Cart,
    protected: false,
    roles: [],
  },
  {
    exact: true,
    path: "/checkout",
    layout: Base,
    component: Checkout,
    protected: true,
    roles: ["guest", "seller", "admin"],
  },
  {
    exact: true,
    path: "/password/reset",
    layout: Base,
    component: Reset,
    protected: false,
    roles: [],
  },
  {
    exact: true,
    path: "/password/reset/:token",
    layout: Base,
    component: PasswordReset,
    protected: false,
    roles: [],
  },
  {
    exact: true,
    path: "/:designation",
    layout: Base,
    component: Produit,
    protected: false,
    roles: [],
  },

  {
    exact: true,
    path: "/admin/customers",
    layout: BaseAdmin,
    component: Customers,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/customers/new",
    layout: BaseAdmin,
    component: AddCustomers,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/customers/:id(\\d+)",
    layout: BaseAdmin,
    component: CustomerDetail,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/customers/:id(\\d+)/edit",
    layout: BaseAdmin,
    component: AddCustomers,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/features",
    layout: BaseAdmin,
    component: Features,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/features/new",
    layout: BaseAdmin,
    component: AddFeatures,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/orders/new",
    layout: BaseAdmin,
    component: AddOrders,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/orders",
    layout: BaseAdmin,
    component: Orders,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/orders/:id(\\d+)",
    layout: BaseAdmin,
    component: OrderDetail,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/orders/:id(\\d+)/edit",
    layout: BaseAdmin,
    component: OrderEdit,
    protected: true,
    roles: ["admin", "guest", "seller"],
  },
  {
    exact: true,
    path: "/admin/settings",
    layout: BaseAdmin,
    component: Settings,
    protected: true,
    roles: ["guest", "seller", "admin"],
  },
  {
    exact: true,
    path: "/admin/products",
    layout: BaseAdmin,
    component: Products,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/products/new",
    layout: BaseAdmin,
    component: AddProducts,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/products/:id(\\d+)",
    layout: BaseAdmin,
    component: ProductDetail,
    protected: true,
    roles: ["admin"],
  },
  {
    exact: true,
    path: "/admin/products/:designation/edit",
    layout: BaseAdmin,
    component: AddProducts,
    protected: true,
    roles: ["admin"],
  },
];
