export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const AJUST_QTE = "AJUST_QTE";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const SAVE_TO_LOCALSTORAGE = "SAVE_TO_LOCALSTORAGE";
export const CLEAN_CART = "CLEAN_CART";
