export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDITE_CATEGORY = "EDITE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_ALL_CATEGORYS = "GET_ALL_CATEGORYS";
export const LOADING_CATEGORYS = "LOADING_CATEGORYS";
export const LOADED_CATEGORYS = "LOADED_PRODUCTS";
