export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDITE_PRODUCT = "EDITE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADED_PRODUCTS = "LOADED_PRODUCTS";
